### ISSUE TITLE
Unhandled Error while reading Petcare Messages

### ISSUE THREAD

**Issue by andreasvogt89** [Shokodev/mauzis#7]
```
2021-07-05 22:07:58:758 error: invalid json response body at https://app.api.surehub.io/api/timeline/household/60617 reason: Unexpected token < in JSON at position 0

(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
at Household.getUpdates (/usr/src/app/src/mauzis/Household.js:95:26)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

```

**Comment by andreasvogt89** [comment]
Surepetcare is no longer part of this repo
