### ISSUE TITLE
Unhandled Error in Telegram API Module

### ISSUE THREAD

**Issue by andreasvogt89** [Shokodev/mauzis#9]
at Telegram.callApi (/usr/src/app/node_modules/telegraf/lib/core/network/client.js:258:19)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 83)

**Comment by andreasvogt89** [comment]
The node-surepetcare module has sent (dependent on load) multiple messages through a for loop which causes errors on the telegram API. There is now a throttling about 200 ms for each message.
